### ISSUE TITLE
Compilation broken on windows/386

### ISSUE THREAD

**Issue by jefferai** [moby/term#23]
At https://github.com/moby/term/blob/25d840ce174ae927ca42f8ddc1bddd01d6004593/term_windows.go#L74 and again in lines 80 and 86, the given standard values are used as an `int` in windows.NewAnsiReader/Writer. However, those values overflow an int if the int is 32-bit, because they're actually (from the x/sys/windows package) uints. As a result, compilation fails:
```
$ GOOS=windows GOARCH=386 go build .
# github.com/moby/term
./term_windows.go:74:39: constant 4294967286 overflows int
./term_windows.go:80:40: constant 4294967285 overflows int
./term_windows.go:86:40: constant 4294967284 overflows int
```

Ref: https://github.com/ory/dockertest/issues/232

**Comment by jefferai** [comment]
I'll note that you're using an `int` because github.com/Azure/go-ansiterm/winterm is using an `int`. So this is probably not a super easy fix. But https://pkg.go.dev/golang.org/x/sys/windows#Handle is definitely returning a uint, and the defined value in that package is definitely in uint territory.

**Comment by cpuguy83** [comment]
Should be fixed by https://github.com/moby/term/commit/721e1b6f516f6032be6e5eeba9b66f70468f5968?

**Comment by cpuguy83** [comment]
Closing since this should be good now, feel free to comment otherwise and we can re-open.

**Comment by jefferai** [comment]
Appears that way -- the commit didn't mention this issue so didn't close it.

Thanks!
