### ISSUE TITLE
Invalid Standard Handle Panic on Windows Server 2012

### ISSUE THREAD

**Issue by FabianKramm** [moby/term#26]
Hello!

Since PR #9 we receive the following panic with the moby/term package on a windows server 2012 within a powershell (it worked fine before that), when trying to call `term.StdStreams()`:

```
panic: Invalid standard handle identifier: 4294967286

goroutine 1 [running]:
github.com/Azure/go-ansiterm/winterm.GetStdFile(0xfffffff6, 0x28, 0xf)
        C:/Users/Administrator/DevSpace/devspace/vendor/github.com/Azure/go-ansiterm/winterm/ansi.go:173 +0x1f6
github.com/moby/term/windows.NewAnsiReader(0xfffffff6, 0xc00000000f, 0x2110980)
        C:/Users/Administrator/DevSpace/devspace/vendor/github.com/moby/term/windows/ansi_reader.go:34 +0x36
github.com/moby/term.StdStreams(0x210ed20, 0xc0000d0000, 0x210ed60, 0xc0000d0008, 0x0, 0x0)
        C:/Users/Administrator/DevSpace/devspace/vendor/github.com/moby/term/term_windows.go:74 +0x1f8
```

Its essentially the same error as described in [for-win](https://github.com/docker/for-win/issues/9770). Maybe I'm mistaken, but I though the PR #9 would replace the github.com/Azure/go-ansiterm package completely, however it seems to be still used in windows/ansi_reader.go, which could cause this issue.

**Comment by n4j** [comment]
@FabianKramm this issue is fixed in the latest version of moby-term. Can you please check?

**Comment by n4j** [comment]
@FabianKramm Did you get a chance to look at this? If we are good here then can we close this issue?

**Comment by FabianKramm** [comment]
@n4j Sorry for the delay, I was quite busy the last days. Just confirmed the newest version works on Windows Server 2012 now, thanks!
