### ISSUE TITLE
License of docs

### ISSUE THREAD

**Issue by rahulmohang** [moby/term#45]
Hi, 

In the page, https://github.com/moby/term/blob/main/README.md, the license for docs is mentioned as CC-BY. Can you please mention the exact CC-BY license and the version of the license?

**Comment by dims** [comment]
We don't have any docs in this repo. Also it looks like you are asking the same question across different projects, so not sure why you opened an issue here.

**Comment by rahulmohang** [comment]
> We don't have any docs in this repo. Also it looks like you are asking the same question across different projects, so not sure why you opened an issue here.

Thank you for the response. The following statement in the README.md, found in this repo, gave an impression that there may be docs in the repo:
"Code and documentation copyright 2015 Docker, inc. Code released under the Apache 2.0 license. Docs released under Creative commons."

Yes, I have raised a few issues related to licenses in the past for different projects.
